### PR TITLE
fix: ingest bool attrs

### LINKED ISSUE #209: Bool attributes are dropped

### PR DESCRIPTION
**Pull request by nityanandagohain**
Fixes #209 

* Previously we directly stored bool values as as string.
* When we added tag attributes support that time this bug got introduct when the attribute wasn't stored in with log line.
* Added changes so that the bool values are stored.

Suggestes and querying work as expected.

### CODE REVIEW

File: exporter/clickhouselogsexporter/exporter.go [hunk 1]
```diff
@@ -342,7 +342,9 @@ func attributesToSlice(attributes pcommon.Map, forceStringValues bool) (response
 				response.FloatValues = append(response.FloatValues, v.Double())
 			case pcommon.ValueTypeBool:
 				// add boolValues in future if it is required
-				response.BoolKeys = append(response.BoolKeys, formatKey(k))
+				// store it as a string in clickhouse for now
+				response.StringKeys = append(response.StringKeys, formatKey(k))
+				response.StringValues = append(response.StringValues, v.AsString())
```
Comment (srikanthccv) [inline exporter/clickhouselogsexporter/exporter.go:347]: > Added changes so that the bool values are stored


I am trying to understand why/where are they dropped currently and why do we need to store them as string?

Comment (srikanthccv) [reply exporter/clickhouselogsexporter/exporter.go:347]: Also this had related bool support and different implementation https://github.com/SigNoz/signoz-otel-collector/pull/183

Comment (nityanandagohain) [reply exporter/clickhouselogsexporter/exporter.go:347]: So they were dropped because previously we stored them in the string key values array. But after adding tag attributes we added bool but it was not actually stored with the log line.

yeah adding the materialized table will be better with new column. Let me make the changes.

File: migrationmanager/migrators/logs/migrations/000008_add_bool.down.sql [hunk 2]
```diff
@@ -0,0 +1,9 @@
+ALTER TABLE signoz_logs.logs ON CLUSTER cluster DROP column IF EXISTS attributes_bool_key;
```
Comment (srikanthccv) [inline migrationmanager/migrators/logs/migrations/000008_add_bool.down.sql:1]: The cluster shouldn't be hardcoded. It should be template env.

**Review by prashant-shahi — APPROVED** [review]

File: migrationmanager/migrators/logs/migrations/000008_add_bool.up.sql [hunk 3]
```diff
@@ -0,0 +1,13 @@
+ALTER TABLE signoz_logs.logs ON CLUSTER {{.SIGNOZ_CLUSTER}} add column IF NOT EXISTS attributes_bool_key Array(String) CODEC(ZSTD(1));
+
+ALTER TABLE signoz_logs.logs ON CLUSTER {{.SIGNOZ_CLUSTER}} add column IF NOT EXISTS attributes_bool_value Array(Bool) CODEC(ZSTD(1));
+
+ALTER TABLE signoz_logs.distributed_logs ON CLUSTER {{.SIGNOZ_CLUSTER}} add column IF NOT EXISTS attributes_bool_key Array(String) CODEC(ZSTD(1));
+
+ALTER TABLE signoz_logs.distributed_logs ON CLUSTER {{.SIGNOZ_CLUSTER}} add column IF NOT EXISTS attributes_bool_value Array(Bool) CODEC(ZSTD(1));
+
+CREATE MATERIALIZED VIEW IF NOT EXISTS  attribute_keys_bool_final_mv ON CLUSTER {{.SIGNOZ_CLUSTER}} TO signoz_logs.logs_attribute_keys AS
```
Comment (srikanthccv) [inline migrationmanager/migrators/logs/migrations/000008_add_bool.up.sql:9]:
```suggestion
CREATE MATERIALIZED VIEW IF NOT EXISTS  signoz_logs.attribute_keys_bool_final_mv ON CLUSTER {{.SIGNOZ_CLUSTER}} TO signoz_logs.logs_attribute_keys AS
```

**Review by srikanthccv — APPROVED** [review]
