### PR TITLE
fix: usage collection for multiple instance of same exporter

### LINKED ISSUE #280: Usage collection data race condition when more than one clickhouse exporter is used in a signle pipeline
Usage collection data race condition when more than one clickhouse exporter is used in a signle pipeline

so if there are two clickhouse logs exporters `clickhouselogs/1`, `clickhouselogs/2`

----
**previously**
both used the same metric
signoz_logs_count{collector_id} = count of exporter 1 + count of exporter 2

and while exporting usage both exported the same data

----
**We needed to change it to**

signoz_logs_count{collector_id, exported_id_1} = count exporter 1 
signoz_logs_count{collector_id, exported_id_2 } = count exporter 2

and while exporting 
exporter 1 exports `signoz_logs_count{collector_id, exported_id_1} `
exporter 2 exports `signoz_logs_count{collector_id, exported_id_2 } `

### PR DESCRIPTION
**Pull request by nityanandagohain**
Fixes #280 

## Summary by CodeRabbit

- **New Features**
	- Enhanced logging, metrics, and trace exporters with unique identification using UUIDs to improve data filtering and management.
- **Refactor**
	- Updated various exporter components to include UUIDs for unique identification.
	- Modified data tagging and filtering mechanisms across logs, metrics, and traces exporters to utilize UUIDs.

### CODE REVIEW

File: exporter/clickhouselogsexporter/usage.go [hunk 1]
```diff
@@ -32,23 +33,26 @@ var (
...
-func UsageExporter(metrics []*metricdata.Metric) (map[string]usage.Usage, error) {
+func UsageExporter(metrics []*metricdata.Metric, id uuid.UUID) (map[string]usage.Usage, error) {
 	data := map[string]usage.Usage{}
 	for _, metric := range metrics {
 		if strings.Contains(metric.Descriptor.Name, "signoz_logs_count") {
 			for _, v := range metric.TimeSeries {
-				tenant := v.LabelValues[0].Value
+				if v.LabelValues[0].Value != id.String() {
+					continue
+				}
```
Comment (srikanthccv) [inline exporter/clickhouselogsexporter/usage.go:54]: I'd use the names for comparison instead of index 0, 1 etc.

File: exporter/clickhousemetricsexporter/clickhouse.go [hunk 2]
```diff
@@ -198,7 +199,7 @@ func (ch *clickHouse) GetDBConn() interface{} {
 	return ch.conn
 }
 
-func (ch *clickHouse) Write(ctx context.Context, data *prompb.WriteRequest, metricNameToMeta map[string]base.MetricMeta) error {
+func (ch *clickHouse) Write(ctx context.Context, exporterID uuid.UUID, data *prompb.WriteRequest, metricNameToMeta map[string]base.MetricMeta) error {
```
Comment (srikanthccv) [inline exporter/clickhousemetricsexporter/clickhouse.go:202]: You could make id part of the `NewClickHouse` instead of update the write interface?

File: exporter/clickhousetracesexporter/clickhouse_factory.go [hunk 3]
```diff
@@ -38,7 +39,7 @@ type Factory struct {
 
 // Writer writes spans to storage.
 type Writer interface {
-	WriteBatchOfSpans(span []*Span) error
+	WriteBatchOfSpans(exporterId uuid.UUID, span []*Span) error
```
Comment (srikanthccv) [inline exporter/clickhousetracesexporter/clickhouse_factory.go:42]: Same.

File: exporter/clickhouselogsexporter/usage.go (hunk 1 above)
Comment (nityanandagohain) [reply exporter/clickhouselogsexporter/usage.go:54]: I don't have the name 
image

Comment (srikanthccv) [reply exporter/clickhouselogsexporter/usage.go:54]: `metric.Descriptor.LabelKeys` is what you are looking for. It is a pair wise array with `LabelValues`

**Review by srikanthccv — APPROVED** [review]
usage.go seemed the same everywhere except name check.
